const searchArray = [
  {
    id: 1,
    nickname: "testperson1",
    profile: true,
    password: "password",
    rating: 10,
    skills: ["React.js", "HTML", "CSS"],
    blurb: "check me out 1",
    projects: "marketing stuff, key finding app",
    userImage: "",
  },
  {
    id: 2,
    nickname: "testperson2",
    profile: true,
    password: "password",
    rating: 9,
    skills: ["React.js", "CSS"],
    blurb: "check me out 2",
    projects: "marketing stuff, key finding app",
    userImage: "",
  },
  {
    id: 3,
    nickname: "testperson3",
    profile: true,
    password: "password",
    rating: 9,
    skills: ["Node.js", "HTML", "CSS"],
    blurb: "check me out 3",
    projects: "marketing stuff, key finding app",
    userImage: "",
  },
  {
    id: 4,
    nickname: "testperson4",
    profile: true,
    password: "password",
    rating: 8,
    skills: ["HTML", "CSS"],
    blurb: "check me out 4",
    projects: "marketing stuff, key finding app",
    userImage: "",
  },
  {
    id: 5,
    nickname: "testperson5",
    profile: false,
    password: "password",
    rating: 4,
    skills: ["Javascript", "HTML", "CSS"],
    blurb: "check me out 5",
    projects: "marketing stuff, key finding app",
    userImage: "",
  },
];

export default searchArray;
